name: Print Software Versions
on:
  push:
    branches: 
      - LW11
jobs:
  PrintLanguageVersions:
    runs-on: ubuntu-latest
    steps:
      - name: Print Node Version
        run: node --version

  PrintDBMSVersions:
    runs-on: ubuntu-latest
    needs: [PrintLanguageVersions]
    steps:
      - name: Print Oracle SQL*Plus Version
        run: sqlplus -V
